-- Skema reward-BPS untuk Turso (libSQL / SQLite)

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','ketua','user')),
  divisi TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kandidat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama TEXT NOT NULL,
  divisi TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS voting (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  internal_id INTEGER NOT NULL REFERENCES kandidat(id) ON DELETE CASCADE,
  eksternal_id INTEGER NOT NULL REFERENCES kandidat(id) ON DELETE CASCADE,
  skp INTEGER DEFAULT 0,
  kjk INTEGER DEFAULT 0,
  total INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS penilaian (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kandidat_id INTEGER UNIQUE REFERENCES kandidat(id) ON DELETE CASCADE,
  skp INTEGER,
  kjk INTEGER,
  total INTEGER
);

CREATE TABLE IF NOT EXISTS sesi_final (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status TEXT DEFAULT 'tutup' CHECK (status IN ('buka','tutup')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS final_vote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kandidat_id INTEGER NOT NULL REFERENCES kandidat(id) ON DELETE CASCADE,
  sesi_id INTEGER REFERENCES sesi_final(id) ON DELETE CASCADE,
  total_nilai INTEGER NOT NULL DEFAULT 0,
  jawaban1 INTEGER, jawaban2 INTEGER, jawaban3 INTEGER, jawaban4 INTEGER, jawaban5 INTEGER,
  jawaban6 INTEGER, jawaban7 INTEGER, jawaban8 INTEGER, jawaban9 INTEGER, jawaban10 INTEGER
);
